### Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Loading the Dataset

In [ ]:
df=pd.read_csv('Dataset/car_performance.csv')

### Data Analysis

In [ ]:
df.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   
5  15.0          8         429.0         198    4341          10.0   
6  14.0          8         454.0         220    4354           9.0   
7  14.0          8         440.0         215    4312           8.5   
8  14.0          8         455.0         225    4425          10.0   
9  15.0          8         390.0         190    3850           8.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino  
5          70       1           ford galaxie 500  
6          70       1           chevrolet impala  
7          70       1          plymouth fury iii  
8          70       1           pontiac catalina  
9          70       1         amc ambassador dpl

In [ ]:
df.shape

(398, 9)

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(5), object(1)
memory usage: 28.1+ KB


In [ ]:
df.nunique()

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model year       13
origin            3
car name        305
dtype: int64

In [ ]:
df.origin.unique()

array([1, 3, 2])

### Handiling the Missing Values

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [ ]:
# There is no Null Value in the data set

### Lable encoding

In [ ]:
# There is no Categorial value other than the car name (car name is not used for the performance predecting so we can drop the car name column), so we need not to do the label encoding

### Droping the car name column

In [ ]:
df=df.iloc[:,:-1]

In [ ]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin  
0          70       1  
1          70       1  
2          70       1  
3          70       1  
4          70       1

### Splitting the dataset into dependent and independent Variable

In [ ]:
x=df.iloc[:,1:]

In [ ]:
y=df.iloc[:,0]

In [ ]:
x.head()

cylinders  displacement  horsepower  weight  acceleration  model year  \
0          8         307.0         130    3504          12.0          70   
1          8         350.0         165    3693          11.5          70   
2          8         318.0         150    3436          11.0          70   
3          8         304.0         150    3433          12.0          70   
4          8         302.0         140    3449          10.5          70   

   origin  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

### Splitting the dataset into train and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((318, 7), (80, 7), (318,), (80,))

### Normalizing the values

In [ ]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
x_train=sd.fit_transform(x_train)
x_test=sd.fit_transform(x_test)

In [ ]:
x_train

array([[ 0.31361269,  0.36208368, -0.36028555, ...,  0.5196298 ,
        -0.29742399, -0.69753728],
       [-0.86661022, -1.03773964, -1.00481077, ...,  1.31198595,
         1.06541218,  1.80886787],
       [ 1.49383561,  1.96188176,  2.21781535, ..., -1.20914727,
         0.24771047, -0.69753728],
       ...,
       [-0.86661022, -0.9901266 , -1.44308793, ...,  2.1403583 ,
         0.52027771,  0.55566529],
       [ 1.49383561,  1.49527399,  1.26391802, ..., -0.74093682,
        -1.38769293, -0.69753728],
       [-0.86661022, -0.6092223 , -0.05091344, ...,  0.05141934,
        -0.02485676,  0.55566529]])

# Model Building

### Implementing the RandomForestRegression Algorithm

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf = RandomForestRegressor(n_estimators=30,random_state=0)

In [ ]:
rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=30, random_state=0)

## Predicting the Value

In [ ]:
y_pred = rf.predict(x_test)

In [ ]:
y_pred

array([15.95333333, 30.6       , 31.13333333, 27.21333333, 15.84666667,
       14.01666667, 32.60333333, 26.1       , 24.59666667, 14.36666667,
       35.80333333, 19.54666667, 24.75333333, 18.08      , 28.08333333,
       15.        , 33.05      , 37.68333333, 18.44666667, 23.15333333,
       17.1       , 18.73      , 29.83666667, 28.93333333, 26.99666667,
       26.12666667, 34.61      , 26.51333333, 35.71666667, 23.57666667,
       15.58666667, 34.23333333, 14.46333333, 13.65      , 23.53333333,
       13.15      , 34.19666667, 11.7       , 33.33666667, 20.40333333,
       28.61333333, 29.40333333, 37.87      , 11.16666667, 20.58666667,
       21.13      , 31.33666667, 19.14      , 18.07333333, 17.82666667,
       18.26666667, 17.97666667, 25.73      , 27.51333333, 25.50666667,
       14.08333333, 26.15666667, 25.84666667, 19.56666667, 20.40333333,
       21.79333333, 25.53      , 13.96666667, 13.4       , 27.88      ,
       23.11666667, 28.21666667, 15.81333333, 30.93333333, 36.49

## Model Evaluation

In [ ]:
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
acc = r2_score(y_test, y_pred)

In [ ]:
acc

0.8570363544939325

In [ ]:
err=np.sqrt(mean_squared_error(y_test,y_pred))

In [ ]:
err

2.7436940578959117

### Exporting the model

In [ ]:
import pickle

In [ ]:
pickle.dump(rf,open('RFregression.pkl','wb'))